#!/bin/sh

# Build frontend
cd $PWD/front-end-3.0 && npm run build && cd .. &&
# Copy frontend to backend
cp -r $PWD/front-end-3.0/public $PWD/server/static &&
# Fix imports 
find $PWD/server/static -type f -exec sed -i 's@"/build/bundle@"/static/build/bundle@g' {} \; &&
echo "Successfully built frontend"
# Run backend
cd $PWD/server && env RUST_LOG=actix_web ~/.cargo/bin/cargo run --release && cd .. 
